### ISSUE TITLE
Resolution scaling on Mac

### ISSUE THREAD

**Issue by atsb** [dashodanger/EDGE-classic#104]
So on Version 1.1, increasing the resolution slowly pushes the image off to the right side of the screen
![screen](https://user-images.githubusercontent.com/44937323/162824252-15e5f3b0-90df-49cf-91e3-5405a442cbc7.png)

**Comment by dashodanger** [comment]
I won't bug you with identical responses on three issues, but I think I can get my hands on some Apple hardware to try to better address this stuff versus what are essentially blind guesses. Unless you know of a good way to virtualize the environment...I had a Big Sur VM running but it was...not the most successful endeavor

**Comment by dashodanger** [comment]
Yeah, I noticed :(
If I can't snag my buddy's Macbook, I'll probably book a little AWS Mac EC2 time...either way, I'll update this when I have a chance to do one or the other.

**Comment by dashodanger** [comment]
Haven't built it on Mac hardware yet, but with https://github.com/dashodanger/EDGE-classic/commit/3ebce52cab1879331db4297f9dd9b89f75abf922 I had a lot better results when changing resolutions when fullscreen.

**Comment by atsb** [comment]
I'll give it a test later today and let you know

**Comment by atsb** [comment]
So this is way better now, I would say, even fixed.

**Comment by dashodanger** [comment]
Awesome, I'll go ahead and close this until/unless it crops up again. Thanks for the heads up.
