### ISSUE TITLE
DOOMWADDIR not working

### ISSUE THREAD

**Issue by andwj** [dashodanger/EDGE-classic#186]
DOOMWADDIR and DOOMWADPATH support is not working, since the results of FS_ReadDir() are relative to the path it is given, but you don't do a FS_Join() to get the full path of those filenames.

I suggest updating FS_ReadDir() to always join the given path onto the results, since most usages of FS_ReadDir() need it anyway.  The one case I noticed to fixed is CMD_Dir (in console code) would need a PATH_GetFilename() on the results to keep the output nice.

Another thing I suggest is treating both these environment vars in a uniform way, namely that once you convert DOOMWADPATH into a list of directories, simply add DOOMWADDIR to this list (assuming it exists).

**Comment by dashodanger** [comment]
I'm going to guess you're on a non-Windows environment? I think i_main (on Windows only) sets the current directory to the executable folder as part of startup, which is why things with relative paths have been working for it, but not other operating systems. I'll see what I can do about moving away from the reliance on relative pathing.

**Comment by dashodanger** [comment]
I just pushed https://github.com/dashodanger/EDGE-classic/commit/473885e6f501b58e57d713f03dc1e999cb9d362f to address your concerns. A quick check on Windows and my FreeBSD VM seems to look good, but I'll keep this open in case you find something that's still lacking.

**Comment by dashodanger** [comment]
Quick note, you'll want to sync up with at least https://github.com/dashodanger/EDGE-classic/commit/b44402da70f3b57593a548d3f354cf650c3dfb82 to test, as I had to fix a couple of savegame functions as a result of FS_ReadDir storing full paths now

**Comment by andwj** [comment]
Yep works fine now.
