### ISSUE TITLE
Sky Texture Issue on M1 builds

### ISSUE THREAD

**Issue by dashodanger** [dashodanger/EDGE-classic#37]
As reported by @atsb , the sky texture seems to be clamped starting at a vertical line in the middle of the player's viewpoint. I've attached a version of r_sky.cc with explicit GL_REPEAT flags added for testing.
[r_sky.zip](https://github.com/dashodanger/EDGE-classic/files/7697727/r_sky.zip)

**Comment by atsb** [comment]
Much better!
<img width="504" alt="edge-classic-m1" src="https://user-images.githubusercontent.com/44937323/145702111-38f34df0-fafa-4c5a-9fa7-f58ec8e128b7.png">

Some tiny black lines where the sky is stitched together, but that is quite minor.

**Comment by dashodanger** [comment]
I noticed that too...I might see if I can reduce the GL_REPEAT to not cover the entire coordinate set and maybe blur those at least. I think I can test that part on my own machine, as those lines look exactly what I'm seeing on this end.

**Comment by dashodanger** [comment]
It looks like those lines disappear when I set the cvar r_dumbclamp to 1...if this works for you, then perhaps I can add the GL_REPEAT and r_dumbclamp defaulting to 1 as #ifdefs for Apple Silicon

**Comment by atsb** [comment]
Seems to be the same yes

**Comment by dashodanger** [comment]
I committed https://github.com/dashodanger/EDGE-classic/commit/f9737aca4b03b099844405727cb3540279aebbc2 which should hopefully work without issue. I don't think the GL_REPEAT lines would do harm if left in for everyone, but I figured I'd change the known behavior on other platforms as little as possible.

**Comment by dashodanger** [comment]
Gonna close this one up, as I think it's handled, but let me know and I can reopen it.
